import { Product, Category, ProductStatus } from '@/lib/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Experience the future of mobile technology with the Samsung Galaxy S24 Ultra. Featuring a stunning Dynamic AMOLED 2X display, a pro-grade camera system with groundbreaking AI-powered features, and the fastest processor ever in a Galaxy, this phone is designed to impress.',
    basePrice: 1299.99,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/s24ultra/800/800', 'https://picsum.photos/seed/s24ultra-2/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/s24ultra/400/400',
    brand: 'Samsung',
    isOnSale: true,
    salePrice: 1199.99,
    tags: ['electronics', 'featured', 'smartphone', 'samsung'],
    specifications: {
      'Display': '6.8" Dynamic AMOLED 2X',
      'Resolution': '3088 x 1440 (Quad HD+)',
      'Processor': 'Snapdragon 8 Gen 3 for Galaxy',
      'RAM': '12GB',
      'Storage': '256GB',
      'Main Camera': '200MP Wide-angle',
      'Battery': '5000mAh',
    },
    hasVariants: true,
    variants: [
      {
        id: '1-1',
        productId: '1',
        sku: 'S24U-256-BLK',
        storeId: 'STORE-1',
        name: 'Samsung Galaxy S24 Ultra 256GB Black',
        attributes: { color: 'Black', storage: '256GB' },
        price: 1299.99,
        isActive: true,
        images: [],
        stock: 100,
        reservedStock: 10,
        trackInventory: true,
        isShippable: true,
        isOnSale: false,
      },
      {
        id: '1-2',
        productId: '1',
        sku: 'S24U-512-BLK',
        storeId: 'STORE-1',
        name: 'Samsung Galaxy S24 Ultra 512GB Black',
        attributes: { color: 'Black', storage: '512GB' },
        price: 1419.99,
        isActive: true,
        images: [],
        stock: 50,
        reservedStock: 5,
        trackInventory: true,
        isShippable: true,
        isOnSale: false,
      },
    ],
  },
  {
    id: '2',
    name: 'Apple iPad Pro',
    description: 'The ultimate iPad experience. With the powerful Apple M2 chip, a stunning Liquid Retina XDR display, and blazing-fast 5G, the iPad Pro is a versatile tool for work, creativity, and entertainment.',
    basePrice: 1099.0,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/ipadpro/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/ipadpro/400/400',
    brand: 'Apple',
    tags: ['electronics', 'tablet', 'apple', 'ipad'],
    specifications: {
      'Display': '12.9-inch Liquid Retina XDR',
      'Chip': 'Apple M2',
      'Storage': '256GB',
      'Camera': '12MP Wide and 10MP Ultra Wide',
    },
    hasVariants: true,
    variants: [
      {
        id: '2-1',
        productId: '2',
        sku: 'IPADPRO-256-SLV',
        storeId: 'STORE-1',
        name: 'Apple iPad Pro 256GB Silver',
        attributes: { color: 'Silver', storage: '256GB' },
        price: 1099.0,
        isActive: true,
        images: [],
        stock: 80,
        reservedStock: 8,
        trackInventory: true,
        isShippable: true,
        isOnSale: false,
      },
      {
        id: '2-2',
        productId: '2',
        sku: 'IPADPRO-512-SLV',
        storeId: 'STORE-1',
        name: 'Apple iPad Pro 512GB Silver',
        attributes: { color: 'Silver', storage: '512GB' },
        price: 1299.0,
        isActive: true,
        images: [],
        stock: 40,
        reservedStock: 4,
        trackInventory: true,
        isShippable: true,
        isOnSale: false,
      },
    ],
  },
  {
    id: '3',
    name: 'Google Pixel 8 Pro',
    description: 'The most advanced Pixel camera yet, with a powerful new Google Tensor G3 chip and a stunning 6.7-inch Super Actua display.',
    basePrice: 999.0,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/pixel8pro/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/pixel8pro/400/400',
    brand: 'Google',
    tags: ['electronics', 'smartphone', 'google', 'pixel'],
    specifications: {
      'Display': '6.7" Super Actua display',
      'Processor': 'Google Tensor G3',
      'RAM': '12GB',
      'Storage': '128GB',
    },
  },
  {
    id: '4',
    name: 'Samsung Galaxy Tab S9 Ultra',
    description: 'The largest and most powerful Galaxy tablet yet, with a massive 14.6-inch Dynamic AMOLED 2X display and the S Pen included.',
    basePrice: 1199.99,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/tabs9ultra/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/tabs9ultra/400/400',
    brand: 'Samsung',
    tags: ['electronics', 'tablet', 'samsung', 'android'],
  },
  {
    id: '5',
    name: 'OnePlus 12',
    description: 'The new flagship from OnePlus, with a stunning 2K 120Hz ProXDR Display, the latest Snapdragon 8 Gen 3 processor, and a Hasselblad camera system.',
    basePrice: 799.0,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/oneplus12/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/oneplus12/400/400',
    brand: 'OnePlus',
    tags: ['electronics', 'smartphone', 'oneplus', 'android'],
  },
  {
    id: '6',
    name: 'Microsoft Surface Pro 9',
    description: 'The versatility of a tablet with the performance of a laptop. The Surface Pro 9 is a 2-in-1 device that can handle any task.',
    basePrice: 999.99,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/surfacepro9/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/surfacepro9/400/400',
    brand: 'Microsoft',
    tags: ['electronics', 'tablet', 'microsoft', 'windows'],
  },
  {
    id: '7',
    name: 'Xiaomi 14 Ultra',
    description: 'A smartphone designed for photographers, with a Leica professional optical lens and a 1-inch main camera sensor.',
    basePrice: 1499.0,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/xiaomi14ultra/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/xiaomi14ultra/400/400',
    brand: 'Xiaomi',
    tags: ['electronics', 'smartphone', 'xiaomi', 'camera'],
  },
  {
    id: '8',
    name: 'Lenovo Tab P12 Pro',
    description: 'A premium Android tablet with a stunning 12.6-inch AMOLED display and a powerful Snapdragon 870 processor.',
    basePrice: 699.99,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/lenovotabp12/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/lenovotabp12/400/400',
    brand: 'Lenovo',
    tags: ['electronics', 'tablet', 'lenovo', 'android'],
  },
  {
    id: '9',
    name: 'Asus ROG Phone 8 Pro',
    description: 'The ultimate gaming smartphone, with a powerful Snapdragon 8 Gen 3 processor, a 165Hz AMOLED display, and AirTrigger controls.',
    basePrice: 1199.99,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/rogphone8/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/rogphone8/400/400',
    brand: 'Asus',
    tags: ['electronics', 'smartphone', 'gaming', 'asus'],
  },
  {
    id: '10',
    name: 'Amazon Fire Max 11',
    description: 'Amazon\'s largest and most powerful tablet, with a brilliant 11-inch display and a fast octa-core processor.',
    basePrice: 229.99,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/firemax11/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/firemax11/400/400',
    brand: 'Amazon',
    tags: ['electronics', 'tablet', 'amazon', 'fireos'],
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    productCount: 10,
    children: [
      {
        id: '1-1',
        name: 'Smartphones',
        productCount: 5,
      },
      {
        id: '1-2',
        name: 'Tablets',
        productCount: 5,
      },
    ],
  },
];

export const getProductById = (id: string): Product | undefined => {
  return mockProducts.find((product) => product.id === id);
};