import { Product, Category, ProductStatus } from '@/lib/types';
import {
  InventoryItem,
  ItemStatus,
  MovementType,
  StockMovement,
} from '@/app/(main)/inventory/_lib/types';
import {
  PurchaseOrder,
  PurchaseOrderStatus,
  PaymentStatus,
  ReceiptStatus,
  Supplier,
  SupplierStatus,
} from '@/app/(main)/purchase/_lib/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Experience the future of mobile technology with the Samsung Galaxy S24 Ultra. Featuring a stunning Dynamic AMOLED 2X display, a pro-grade camera system with groundbreaking AI-powered features, and the fastest processor ever in a Galaxy, this phone is designed to impress.',
    basePrice: 19499850,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/s24ultra/800/800', 'https://picsum.photos/seed/s24ultra-2/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/s24ultra/400/400',
    brand: 'Samsung',
    isOnSale: true,
    salePrice: 17999850,
    tags: ['electronics', 'featured', 'smartphone', 'samsung'],
    specifications: {
      'Display': '6.8" Dynamic AMOLED 2X',
      'Resolution': '3088 x 1440 (Quad HD+)',
      'Processor': 'Snapdragon 8 Gen 3 for Galaxy',
      'RAM': '12GB',
      'Storage': '256GB',
      'Main Camera': '200MP Wide-angle',
      'Battery': '5000mAh',
    },
    hasVariants: true,
    variants: [
      {
        id: '1-1',
        productId: '1',
        sku: 'S24U-256-BLK',
        storeId: 'STORE-1',
        name: 'Samsung Galaxy S24 Ultra 256GB Black',
        attributes: { color: 'Black', storage: '256GB' },
        price: 19499850,
        isActive: true,
        images: [],
        stock: 100,
        reservedStock: 10,
        trackInventory: true,
        isShippable: true,
        isOnSale: false,
      },
      {
        id: '1-2',
        productId: '1',
        sku: 'S24U-512-BLK',
        storeId: 'STORE-1',
        name: 'Samsung Galaxy S24 Ultra 512GB Black',
        attributes: { color: 'Black', storage: '512GB' },
        price: 21299850,
        isActive: true,
        images: [],
        stock: 50,
        reservedStock: 5,
        trackInventory: true,
        isShippable: true,
        isOnSale: false,
      },
    ],
  },
  {
    id: '2',
    name: 'Apple iPad Pro',
    description: 'The ultimate iPad experience. With the powerful Apple M2 chip, a stunning Liquid Retina XDR display, and blazing-fast 5G, the iPad Pro is a versatile tool for work, creativity, and entertainment.',
    basePrice: 16485000,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/ipadpro/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/ipadpro/400/400',
    brand: 'Apple',
    tags: ['electronics', 'tablet', 'apple', 'ipad'],
    specifications: {
      'Display': '12.9-inch Liquid Retina XDR',
      'Chip': 'Apple M2',
      'Storage': '256GB',
      'Camera': '12MP Wide and 10MP Ultra Wide',
    },
    hasVariants: true,
    variants: [
      {
        id: '2-1',
        productId: '2',
        sku: 'IPADPRO-256-SLV',
        storeId: 'STORE-1',
        name: 'Apple iPad Pro 256GB Silver',
        attributes: { color: 'Silver', storage: '256GB' },
        price: 16485000,
        isActive: true,
        images: [],
        stock: 80,
        reservedStock: 8,
        trackInventory: true,
        isShippable: true,
        isOnSale: false,
      },
      {
        id: '2-2',
        productId: '2',
        sku: 'IPADPRO-512-SLV',
        storeId: 'STORE-1',
        name: 'Apple iPad Pro 512GB Silver',
        attributes: { color: 'Silver', storage: '512GB' },
        price: 19485000,
        isActive: true,
        images: [],
        stock: 40,
        reservedStock: 4,
        trackInventory: true,
        isShippable: true,
        isOnSale: false,
      },
    ],
  },
  {
    id: '3',
    name: 'Google Pixel 8 Pro',
    description: 'The most advanced Pixel camera yet, with a powerful new Google Tensor G3 chip and a stunning 6.7-inch Super Actua display.',
    basePrice: 14985000,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/pixel8pro/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/pixel8pro/400/400',
    brand: 'Google',
    tags: ['electronics', 'smartphone', 'google', 'pixel'],
    specifications: {
      'Display': '6.7" Super Actua display',
      'Processor': 'Google Tensor G3',
      'RAM': '12GB',
      'Storage': '128GB',
    },
  },
  {
    id: '4',
    name: 'Samsung Galaxy Tab S9 Ultra',
    description: 'The largest and most powerful Galaxy tablet yet, with a massive 14.6-inch Dynamic AMOLED 2X display and the S Pen included.',
    basePrice: 17999850,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/tabs9ultra/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/tabs9ultra/400/400',
    brand: 'Samsung',
    tags: ['electronics', 'tablet', 'samsung', 'android'],
  },
  {
    id: '5',
    name: 'OnePlus 12',
    description: 'The new flagship from OnePlus, with a stunning 2K 120Hz ProXDR Display, the latest Snapdragon 8 Gen 3 processor, and a Hasselblad camera system.',
    basePrice: 11985000,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/oneplus12/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/oneplus12/400/400',
    brand: 'OnePlus',
    tags: ['electronics', 'smartphone', 'oneplus', 'android'],
  },
  {
    id: '6',
    name: 'Microsoft Surface Pro 9',
    description: 'The versatility of a tablet with the performance of a laptop. The Surface Pro 9 is a 2-in-1 device that can handle any task.',
    basePrice: 14999850,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/surfacepro9/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/surfacepro9/400/400',
    brand: 'Microsoft',
    tags: ['electronics', 'tablet', 'microsoft', 'windows'],
  },
  {
    id: '7',
    name: 'Xiaomi 14 Ultra',
    description: 'A smartphone designed for photographers, with a Leica professional optical lens and a 1-inch main camera sensor.',
    basePrice: 22485000,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/xiaomi14ultra/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/xiaomi14ultra/400/400',
    brand: 'Xiaomi',
    tags: ['electronics', 'smartphone', 'xiaomi', 'camera'],
  },
  {
    id: '8',
    name: 'Lenovo Tab P12 Pro',
    description: 'A premium Android tablet with a stunning 12.6-inch AMOLED display and a powerful Snapdragon 870 processor.',
    basePrice: 10499850,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/lenovotabp12/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/lenovotabp12/400/400',
    brand: 'Lenovo',
    tags: ['electronics', 'tablet', 'lenovo', 'android'],
  },
  {
    id: '9',
    name: 'Asus ROG Phone 8 Pro',
    description: 'The ultimate gaming smartphone, with a powerful Snapdragon 8 Gen 3 processor, a 165Hz AMOLED display, and AirTrigger controls.',
    basePrice: 17999850,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-1',
    images: ['https://picsum.photos/seed/rogphone8/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/rogphone8/400/400',
    brand: 'Asus',
    tags: ['electronics', 'smartphone', 'gaming', 'asus'],
  },
  {
    id: '10',
    name: 'Amazon Fire Max 11',
    description: 'Amazon\'s largest and most powerful tablet, with a brilliant 11-inch display and a fast octa-core processor.',
    basePrice: 3449850,
    status: ProductStatus.PUBLISHED,
    categoryId: '1-2',
    images: ['https://picsum.photos/seed/firemax11/800/800'],
    thumbnailUrl: 'https://picsum.photos/seed/firemax11/400/400',
    brand: 'Amazon',
    tags: ['electronics', 'tablet', 'amazon', 'fireos'],
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    productCount: 10,
    children: [
      {
        id: '1-1',
        name: 'Smartphones',
        productCount: 5,
      },
      {
        id: '1-2',
        name: 'Tablets',
        productCount: 5,
      },
    ],
  },
];

export const getProductById = (id: string): Product | undefined => {
  return mockProducts.find((product) => product.id === id);
};

export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    sku: 'SKU001',
    storeId: 'STORE-1',
    name: 'Product A',
    description: 'Description for Product A',
    price: 1500000,
    quantity: 50,
    reorderPoint: 20,
    optimalStock: 100,
    status: ItemStatus.ACTIVE,
    categories: ['Category 1'],
    tags: ['Tag 1'],
    reservedQuantity: 5,
    createdAt: new Date('2024-03-15T10:00:00Z'),
    updatedAt: new Date('2024-03-15T10:00:00Z'),
    version: 1,
    batches: [
      {
        id: 'BATCH-001',
        inventoryItemId: '1',
        batchNumber: 'B001',
        expiryDate: new Date('2025-12-31T00:00:00Z'),
        quantity: 50,
        createdAt: new Date('2024-03-15T10:00:00Z'),
      },
    ],
  },
  {
    id: '2',
    sku: 'SKU002',
    storeId: 'STORE-1',
    name: 'Product B',
    description: 'Description for Product B',
    price: 2250000,
    quantity: 15,
    reorderPoint: 30,
    optimalStock: 150,
    status: ItemStatus.ACTIVE,
    categories: ['Category 2'],
    tags: ['Tag 2'],
    reservedQuantity: 0,
    createdAt: new Date('2024-03-15T09:30:00Z'),
    updatedAt: new Date('2024-03-15T09:30:00Z'),
    version: 1,
    batches: [
      {
        id: 'BATCH-002',
        inventoryItemId: '2',
        batchNumber: 'B002',
        expiryDate: new Date('2025-12-31T00:00:00Z'),
        quantity: 15,
        createdAt: new Date('2024-03-15T09:30:00Z'),
      },
    ],
  },
  {
    id: '3',
    sku: 'SKU003',
    storeId: 'STORE-1',
    name: 'Product C',
    description: 'Description for Product C',
    price: 3000000,
    quantity: 0,
    reorderPoint: 10,
    optimalStock: 50,
    status: ItemStatus.OUT_OF_STOCK,
    categories: ['Category 1'],
    tags: ['Tag 3'],
    reservedQuantity: 0,
    createdAt: new Date('2024-03-15T08:45:00Z'),
    updatedAt: new Date('2024-03-15T08:45:00Z'),
    version: 1,
    batches: [],
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'Supplier A',
    storeId: 'STORE-1',
    code: 'SUP-A',
    contactPerson: 'John Doe',
    email: 'john.doe@suppliera.com',
    phone: '123-456-7890',
    address: {
      street: '123 Supplier St',
      city: 'Supply City',
      state: 'CA',
      zipCode: '12345',
      country: 'USA',
    },
    status: SupplierStatus.ACTIVE,
    categories: ['Raw Materials'],
    rating: 4.5,
    createdAt: new Date('2023-01-15T09:00:00Z'),
    updatedAt: new Date('2023-01-15T09:00:00Z'),
    totalOrderValue: 225000000,
    orderCount: 10,
  },
  {
    id: '2',
    name: 'Supplier B',
    storeId: 'STORE-1',
    code: 'SUP-B',
    contactPerson: 'Jane Smith',
    email: 'jane.smith@supplierb.com',
    phone: '098-765-4321',
    address: {
      street: '456 Supplier Ave',
      city: 'Supply City',
      state: 'CA',
      zipCode: '12345',
      country: 'USA',
    },
    status: SupplierStatus.ACTIVE,
    categories: ['Packaging'],
    rating: 4.0,
    createdAt: new Date('2023-02-20T10:00:00Z'),
    updatedAt: new Date('2023-02-20T10:00:00Z'),
    totalOrderValue: 375000000,
    orderCount: 15,
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'PO-2024-001',
    orderNumber: 'PO-2024-001',
    storeId: 'STORE-1',
    supplierId: '1',
    createdById: 'USER-1',
    status: PurchaseOrderStatus.DRAFT,
    paymentStatus: PaymentStatus.PENDING,
    subtotal: 15000000,
    tax: 1500000,
    shipping: 750000,
    total: 17250000,
    expectedDeliveryDate: new Date('2024-03-15T00:00:00Z'),
    deliveryAddress: {
      street: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      zipCode: '12345',
      country: 'USA',
    },
    items: [
      {
        id: '1',
        orderId: 'PO-2024-001',
        inventoryItemId: '1',
        storeId: 'STORE-1',
        sku: 'SKU001',
        name: 'Product A',
        quantity: 10,
        receivedQuantity: 0,
        batchNumber: 'B001',
        unitPrice: 1500000,
        subtotal: 15000000,
        tax: 1500000,
        total: 16500000,
        receiptStatus: ReceiptStatus.PENDING,
        createdAt: new Date('2024-03-01T10:00:00Z'),
        updatedAt: new Date('2024-03-15T10:00:00Z'),
      },
    ],
    createdAt: new Date('2024-03-01T10:00:00Z'),
    updatedAt: new Date('2024-03-15T10:00:00Z'),
    version: 1,
  },
  {
    id: 'PO-2024-002',
    orderNumber: 'PO-2024-002',
    storeId: 'STORE-1',
    supplierId: '2',
    createdById: 'USER-2',
    status: PurchaseOrderStatus.SENT,
    paymentStatus: PaymentStatus.PENDING,
    subtotal: 37500000,
    tax: 3750000,
    shipping: 1500000,
    total: 42750000,
    expectedDeliveryDate: new Date('2024-04-01T00:00:00Z'),
    deliveryAddress: {
      street: '456 Oak Ave',
      city: 'Othertown',
      state: 'CA',
      zipCode: '54321',
      country: 'USA',
    },
    items: [
      {
        id: '2',
        orderId: 'PO-2024-002',
        inventoryItemId: '2',
        storeId: 'STORE-1',
        sku: 'SKU002',
        name: 'Product B',
        quantity: 50,
        receivedQuantity: 0,
        batchNumber: 'B002',
        unitPrice: 750000,
        subtotal: 37500000,
        tax: 3750000,
        total: 41250000,
        receiptStatus: ReceiptStatus.PENDING,
        createdAt: new Date('2024-03-20T11:00:00Z'),
        updatedAt: new Date('2024-03-20T11:00:00Z'),
      },
    ],
    createdAt: new Date('2024-03-20T11:00:00Z'),
    updatedAt: new Date('2024-03-20T11:00:00Z'),
    version: 1,
  },
  {
    id: 'PO-2024-003',
    orderNumber: 'PO-2024-003',
    storeId: 'STORE-1',
    supplierId: '1',
    createdById: 'USER-1',
    status: PurchaseOrderStatus.CONFIRMED,
    paymentStatus: PaymentStatus.PAID,
    subtotal: 75000000,
    tax: 7500000,
    shipping: 2250000,
    total: 84750000,
    expectedDeliveryDate: new Date('2024-04-10T00:00:00Z'),
    deliveryAddress: {
      street: '789 Pine St',
      city: 'Mapleton',
      state: 'CA',
      zipCode: '67890',
      country: 'USA',
    },
    items: [
      {
        id: '3',
        orderId: 'PO-2024-003',
        inventoryItemId: '3',
        storeId: 'STORE-1',
        sku: 'SKU003',
        name: 'Product C',
        quantity: 100,
        receivedQuantity: 0,
        batchNumber: 'B003',
        unitPrice: 750000,
        subtotal: 75000000,
        tax: 7500000,
        total: 82500000,
        receiptStatus: ReceiptStatus.PENDING,
        createdAt: new Date('2024-03-25T12:00:00Z'),
        updatedAt: new Date('2024-03-30T12:00:00Z'),
      },
    ],
    createdAt: new Date('2024-03-25T12:00:00Z'),
    updatedAt: new Date('2024-03-30T12:00:00Z'),
    version: 2,
  },
  {
    id: 'PO-2024-004',
    orderNumber: 'PO-2024-004',
    storeId: 'STORE-1',
    supplierId: '2',
    createdById: 'USER-2',
    status: PurchaseOrderStatus.PARTIALLY_RECEIVED,
    paymentStatus: PaymentStatus.PARTIALLY_PAID,
    subtotal: 1500000,
    tax: 150000,
    shipping: 75000,
    total: 1725000,
    expectedDeliveryDate: new Date('2024-04-15T00:00:00Z'),
    deliveryAddress: {
      street: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      zipCode: '12345',
      country: 'USA',
    },
    items: [
      {
        id: '4',
        orderId: 'PO-2024-004',
        inventoryItemId: '1',
        storeId: 'STORE-1',
        sku: 'SKU001',
        name: 'Product A',
        quantity: 10,
        receivedQuantity: 5,
        batchNumber: 'B004',
        unitPrice: 150000,
        subtotal: 1500000,
        tax: 150000,
        total: 1650000,
        receiptStatus: ReceiptStatus.PARTIALLY_RECEIVED,
        createdAt: new Date('2024-04-01T10:00:00Z'),
        updatedAt: new Date('2024-04-01T10:00:00Z'),
      },
    ],
    createdAt: new Date('2024-04-01T10:00:00Z'),
    updatedAt: new Date('2024-04-01T10:00:00Z'),
    version: 1,
  },
  {
    id: 'PO-2024-005',
    orderNumber: 'PO-2024-005',
    storeId: 'STORE-1',
    supplierId: '1',
    createdById: 'USER-1',
    status: PurchaseOrderStatus.RECEIVED,
    paymentStatus: PaymentStatus.PAID,
    subtotal: 3000000,
    tax: 300000,
    shipping: 150000,
    total: 3450000,
    expectedDeliveryDate: new Date('2024-04-20T00:00:00Z'),
    deliveryAddress: {
      street: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      zipCode: '12345',
      country: 'USA',
    },
    items: [
      {
        id: '5',
        orderId: 'PO-2024-005',
        inventoryItemId: '2',
        storeId: 'STORE-1',
        sku: 'SKU002',
        name: 'Product B',
        quantity: 20,
        receivedQuantity: 20,
        batchNumber: 'B005',
        unitPrice: 150000,
        subtotal: 3000000,
        tax: 300000,
        total: 3300000,
        receiptStatus: ReceiptStatus.RECEIVED,
        createdAt: new Date('2024-04-05T11:00:00Z'),
        updatedAt: new Date('2024-04-05T11:00:00Z'),
      },
    ],
    createdAt: new Date('2024-04-05T11:00:00Z'),
    updatedAt: new Date('2024-04-05T11:00:00Z'),
    version: 1,
  },
  {
    id: 'PO-2024-006',
    orderNumber: 'PO-2024-006',
    storeId: 'STORE-1',
    supplierId: '2',
    createdById: 'USER-2',
    status: PurchaseOrderStatus.CANCELLED,
    paymentStatus: PaymentStatus.CANCELLED,
    subtotal: 4500000,
    tax: 450000,
    shipping: 225000,
    total: 5175000,
    expectedDeliveryDate: new Date('2024-04-25T00:00:00Z'),
    deliveryAddress: {
      street: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      zipCode: '12345',
      country: 'USA',
    },
    items: [],
    createdAt: new Date('2024-04-10T12:00:00Z'),
    updatedAt: new Date('2024-04-10T12:00:00Z'),
    version: 1,
  },
];

export const mockStockMovements: StockMovement[] = [
  {
    id: '1',
    inventoryItemId: '1',
    storeId: 'STORE-1',
    type: MovementType.PURCHASE,
    quantity: 50,
    referenceNumber: 'PO-001',
    notes: 'Regular stock replenishment',
    performedBy: 'User 1',
    createdAt: new Date('2024-03-15T10:00:00Z'),
  },
  {
    id: '2',
    inventoryItemId: '2',
    storeId: 'STORE-1',
    type: MovementType.SALE,
    quantity: -25,
    referenceNumber: 'SO-001',
    notes: 'Customer order',
    performedBy: 'User 2',
    createdAt: new Date('2024-03-15T09:30:00Z'),
  },
  {
    id: '3',
    inventoryItemId: '3',
    storeId: 'STORE-1',
    type: MovementType.ADJUSTMENT,
    quantity: -5,
    referenceNumber: 'ADJ-001',
    notes: 'Damaged inventory removal',
    performedBy: 'User 1',
    createdAt: new Date('2024-03-15T08:45:00Z'),
  },
];